name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (curl, wget, libssl1.1)
      run: |
        apt-get update
        apt-get install curl wget libssl1.1 -y 
    
    - name: Install Java for Embold Scanner
      run: |
        apt-get install openjdk-11-jre -y
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # FIXED STEP: Points to src/Jackett.sln
    # If this fails, the workflow exits and will NOT run the Embold step
    - name: Build with dotnet
      run: dotnet build src/Jackett.sln --configuration Release

    - name: Embold Analyse
      run: |
        curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        curl --silent --location --request GET "${{ vars.EMBOLD_URL_CS }}/api/v1/repositories/6b4e43fd3f19c67fd8ffbb0ab8ce6209/scans/config/download" --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" -o repository-configuration.json
        echo "Download repository configuration file done"
        ./browserstack-codequality-scanner/bin/embold-scanner analyse -u ${{ vars.EMBOLD_URL_CS }} -t ${{ secrets.EMBOLD_TOKEN_CS}} -r 6b4e43fd3f19c67fd8ffbb0ab8ce6209 -b . -d ./embold-data -c ./repository-configuration.json -v
